/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as ChatSettingsRouteImport } from './routes/_chat.settings'
import { Route as ChatResearchRouteImport } from './routes/_chat.research'
import { Route as ChatGithubRouteImport } from './routes/_chat.github'
import { Route as ChatCloudRouteImport } from './routes/_chat.cloud'
import { Route as ChatThreadIdRouteImport } from './routes/_chat.$threadId'
import { Route as ChatResearchIndexRouteImport } from './routes/_chat.research.index'
import { Route as ChatResearchResearchIdThreadIdRouteImport } from './routes/_chat.research.$researchId.$threadId'

const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatSettingsRoute = ChatSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ChatRoute,
} as any)
const ChatResearchRoute = ChatResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => ChatRoute,
} as any)
const ChatGithubRoute = ChatGithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => ChatRoute,
} as any)
const ChatCloudRoute = ChatCloudRouteImport.update({
  id: '/cloud',
  path: '/cloud',
  getParentRoute: () => ChatRoute,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatResearchIndexRoute = ChatResearchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatResearchRoute,
} as any)
const ChatResearchResearchIdThreadIdRoute =
  ChatResearchResearchIdThreadIdRouteImport.update({
    id: '/$researchId/$threadId',
    path: '/$researchId/$threadId',
    getParentRoute: () => ChatResearchRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/$threadId': typeof ChatThreadIdRoute
  '/cloud': typeof ChatCloudRoute
  '/github': typeof ChatGithubRoute
  '/research': typeof ChatResearchRouteWithChildren
  '/settings': typeof ChatSettingsRoute
  '/research/': typeof ChatResearchIndexRoute
  '/research/$researchId/$threadId': typeof ChatResearchResearchIdThreadIdRoute
}
export interface FileRoutesByTo {
  '/$threadId': typeof ChatThreadIdRoute
  '/cloud': typeof ChatCloudRoute
  '/github': typeof ChatGithubRoute
  '/settings': typeof ChatSettingsRoute
  '/': typeof ChatIndexRoute
  '/research': typeof ChatResearchIndexRoute
  '/research/$researchId/$threadId': typeof ChatResearchResearchIdThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/_chat/$threadId': typeof ChatThreadIdRoute
  '/_chat/cloud': typeof ChatCloudRoute
  '/_chat/github': typeof ChatGithubRoute
  '/_chat/research': typeof ChatResearchRouteWithChildren
  '/_chat/settings': typeof ChatSettingsRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/research/': typeof ChatResearchIndexRoute
  '/_chat/research/$researchId/$threadId': typeof ChatResearchResearchIdThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$threadId'
    | '/cloud'
    | '/github'
    | '/research'
    | '/settings'
    | '/research/'
    | '/research/$researchId/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$threadId'
    | '/cloud'
    | '/github'
    | '/settings'
    | '/'
    | '/research'
    | '/research/$researchId/$threadId'
  id:
    | '__root__'
    | '/_chat'
    | '/_chat/$threadId'
    | '/_chat/cloud'
    | '/_chat/github'
    | '/_chat/research'
    | '/_chat/settings'
    | '/_chat/'
    | '/_chat/research/'
    | '/_chat/research/$researchId/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/settings': {
      id: '/_chat/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ChatSettingsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/research': {
      id: '/_chat/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ChatResearchRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/github': {
      id: '/_chat/github'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof ChatGithubRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/cloud': {
      id: '/_chat/cloud'
      path: '/cloud'
      fullPath: '/cloud'
      preLoaderRoute: typeof ChatCloudRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$threadId': {
      id: '/_chat/$threadId'
      path: '/$threadId'
      fullPath: '/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/research/': {
      id: '/_chat/research/'
      path: '/'
      fullPath: '/research/'
      preLoaderRoute: typeof ChatResearchIndexRouteImport
      parentRoute: typeof ChatResearchRoute
    }
    '/_chat/research/$researchId/$threadId': {
      id: '/_chat/research/$researchId/$threadId'
      path: '/$researchId/$threadId'
      fullPath: '/research/$researchId/$threadId'
      preLoaderRoute: typeof ChatResearchResearchIdThreadIdRouteImport
      parentRoute: typeof ChatResearchRoute
    }
  }
}

interface ChatResearchRouteChildren {
  ChatResearchIndexRoute: typeof ChatResearchIndexRoute
  ChatResearchResearchIdThreadIdRoute: typeof ChatResearchResearchIdThreadIdRoute
}

const ChatResearchRouteChildren: ChatResearchRouteChildren = {
  ChatResearchIndexRoute: ChatResearchIndexRoute,
  ChatResearchResearchIdThreadIdRoute: ChatResearchResearchIdThreadIdRoute,
}

const ChatResearchRouteWithChildren = ChatResearchRoute._addFileChildren(
  ChatResearchRouteChildren,
)

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatCloudRoute: typeof ChatCloudRoute
  ChatGithubRoute: typeof ChatGithubRoute
  ChatResearchRoute: typeof ChatResearchRouteWithChildren
  ChatSettingsRoute: typeof ChatSettingsRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatCloudRoute: ChatCloudRoute,
  ChatGithubRoute: ChatGithubRoute,
  ChatResearchRoute: ChatResearchRouteWithChildren,
  ChatSettingsRoute: ChatSettingsRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
