// FILE: ipcChannels.ts
// Purpose: One source of truth for Electron main/preload IPC channel names.

export const DESKTOP_IPC_CHANNELS = {
  wsUrl: "desktop:get-ws-url",
  pickFolder: "desktop:pick-folder",
  saveFile: "desktop:save-file",
  confirm: "desktop:confirm",
  setTheme: "desktop:set-theme",
  contextMenu: "desktop:context-menu",
  openExternal: "desktop:open-external",
  showInFolder: "desktop:show-in-folder",
  clipboardWriteImage: "desktop:clipboard-write-image",
  windowMinimize: "desktop:window-minimize",
  windowToggleMaximize: "desktop:window-toggle-maximize",
  windowClose: "desktop:window-close",
  windowGetState: "desktop:window-get-state",
  windowState: "desktop:window-state",
  menuAction: "desktop:menu-action",
  zoomFactor: "desktop:zoom-factor",
  zoomFactorChanged: "desktop:zoom-factor-changed",
  updateState: "desktop:update-state",
  updateGetState: "desktop:update-get-state",
  updateCheck: "desktop:update-check",
  updateDownload: "desktop:update-download",
  updateInstall: "desktop:update-install",
  notificationsIsSupported: "desktop:notifications-is-supported",
  notificationsShow: "desktop:notifications-show",
  appSnap: {
    getState: "desktop:appsnap:get-state",
    setEnabled: "desktop:appsnap:set-enabled",
    setChord: "desktop:appsnap:set-chord",
    requestPermissions: "desktop:appsnap:request-permissions",
    listPendingCaptures: "desktop:appsnap:list-pending-captures",
    acknowledgeCapture: "desktop:appsnap:acknowledge-capture",
    captured: "desktop:appsnap:captured",
    error: "desktop:appsnap:error",
    state: "desktop:appsnap:state",
  },
} as const;
